import type {
  Client,
  Project,
  Estimate,
  EstimateItem,
  RateItem,
  Note,
  SiteVisit,
  ChecklistItem,
  RFQ,
  Template,
  Settings,
  ActivityItem,
  ProjectTask,
} from "./types";

const id = (prefix: string, n: number) => `${prefix}_${n.toString(36)}`;

export const seedClients: Client[] = [
  { id: id("cl", 1), name: "Damac Properties" },
  { id: id("cl", 2), name: "Better Homes" },
  { id: id("cl", 3), name: "Al Futtaim Logistics" },
  { id: id("cl", 4), name: "Emaar Communities" },
  { id: id("cl", 5), name: "Lulu Group" },
  { id: id("cl", 6), name: "Standard Chartered" },
  { id: id("cl", 7), name: "Aldar Estates" },
  { id: id("cl", 8), name: "Majid Al Futtaim" },
];

export const seedProjects: Project[] = [
  {
    id: "p_1",
    name: "Marina Heights Tower — Annual FM",
    clientId: seedClients[0].id,
    client: "Damac Properties",
    location: "Dubai Marina",
    scope: ["Cleaning", "HVAC", "Pest Control"],
    status: "Quotation Sent",
    value: 482000,
    updated: "2h ago",
    owner: "Ahmed",
    priority: "High",
    dueDate: "May 22",
    next: "Follow-up call with Procurement",
    estimateId: "est_1",
    pinned: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    id: "p_2",
    name: "JLT Cluster B — Reactive MEP",
    clientId: seedClients[1].id,
    client: "Better Homes",
    location: "JLT, Dubai",
    scope: ["MEP", "Electrical", "Plumbing"],
    status: "Pricing",
    value: 138500,
    updated: "5h ago",
    owner: "Ahmed",
    priority: "Medium",
    dueDate: "May 20",
    next: "Finalize manpower rates",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "p_3",
    name: "Al Quoz Warehouse Cleaning",
    clientId: seedClients[2].id,
    client: "Al Futtaim Logistics",
    location: "Al Quoz, Dubai",
    scope: ["Cleaning"],
    status: "Site Visit",
    value: 96000,
    updated: "Yesterday",
    owner: "Ahmed",
    priority: "Medium",
    dueDate: "May 18",
    next: "Site visit scheduled 3pm",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: "p_4",
    name: "Mira Townhouses Landscaping",
    clientId: seedClients[3].id,
    client: "Emaar Communities",
    location: "Mira, Reem",
    scope: ["Landscaping"],
    status: "New",
    value: 0,
    updated: "Today",
    owner: "Ahmed",
    priority: "Low",
    dueDate: "May 25",
    next: "Request scope clarification",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: "p_5",
    name: "Sharjah Corniche Mall HVAC PPM",
    clientId: seedClients[4].id,
    client: "Lulu Group",
    location: "Sharjah",
    scope: ["HVAC"],
    status: "Follow Up",
    value: 215000,
    updated: "2d ago",
    owner: "Ahmed",
    priority: "High",
    dueDate: "May 19",
    next: "Send revised quotation v2",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
  {
    id: "p_6",
    name: "DIFC Office Refresh — Deep Clean",
    clientId: seedClients[5].id,
    client: "Standard Chartered",
    location: "DIFC, Dubai",
    scope: ["Cleaning"],
    status: "Won",
    value: 64500,
    updated: "3d ago",
    owner: "Ahmed",
    priority: "Medium",
    dueDate: "—",
    next: "Hand over to operations",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
  },
  {
    id: "p_7",
    name: "Yas Island Villas Pest Control",
    clientId: seedClients[6].id,
    client: "Aldar Estates",
    location: "Yas Island, Abu Dhabi",
    scope: ["Pest Control"],
    status: "Lost",
    value: 0,
    updated: "1w ago",
    owner: "Ahmed",
    priority: "Low",
    dueDate: "—",
    next: "Lost to incumbent — debrief",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: "p_8",
    name: "Mall of the Emirates Tenant Civil Works",
    clientId: seedClients[7].id,
    client: "Majid Al Futtaim",
    location: "Al Barsha, Dubai",
    scope: ["Civil", "MEP"],
    status: "Pricing",
    value: 312000,
    updated: "4h ago",
    owner: "Ahmed",
    priority: "High",
    dueDate: "May 21",
    next: "Cost-up by EOD Wednesday",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
];

export const seedEstimates: Estimate[] = [
  {
    id: "est_1",
    projectId: "p_1",
    name: "Marina Heights Tower — Annual FM",
    version: "v3 Draft",
    quotationNumber: "QTN-2026-0142",
    validity: "45 days",
    paymentTerms: "30 days net",
    coverLetter:
      "Dear Procurement Team,\n\nPlease find attached our quotation for Marina Heights Tower annual FM services. We've costed against actual site data captured during our visit on 14 May. Happy to walk you through any line item.",
    includeAssumptions: true,
    updatedAt: Date.now() - 1000 * 60 * 12,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
];

export const seedEstimateItems: EstimateItem[] = [
  { id: "ei_1", estimateId: "est_1", item: "C-01", desc: "Monthly cleaning manpower — 4 operatives, day shift", category: "Manpower", unit: "month", qty: 12, cost: 9600, markup: 18, notes: "1 supervisor included" },
  { id: "ei_2", estimateId: "est_1", item: "C-02", desc: "Cleaning consumables (chemicals + paper)", category: "Consumables", unit: "month", qty: 12, cost: 320, markup: 22, notes: "Per 1000 sqm" },
  { id: "ei_3", estimateId: "est_1", item: "H-01", desc: "AHU filter replacement — pleated MERV 8", category: "HVAC", unit: "pc", qty: 64, cost: 38, markup: 25, notes: "Quarterly cycle x4" },
  { id: "ei_4", estimateId: "est_1", item: "H-02", desc: "AHU coil chemical clean", category: "HVAC", unit: "unit", qty: 16, cost: 480, markup: 25, notes: "Twice per year" },
  { id: "ei_5", estimateId: "est_1", item: "P-01", desc: "Pest control — quarterly visits, common areas", category: "Pest Control", unit: "visit", qty: 4, cost: 350, markup: 30, notes: "All BoH areas" },
  { id: "ei_6", estimateId: "est_1", item: "E-01", desc: "Generator inspection — 400 kVA standby", category: "Electrical", unit: "visit", qty: 12, cost: 650, markup: 22, notes: "Monthly PPM" },
  { id: "ei_7", estimateId: "est_1", item: "PL-01", desc: "Plumbing repair allowance", category: "Plumbing", unit: "month", qty: 12, cost: 1200, markup: 15, notes: "Materials excluded" },
];

export const seedRates: RateItem[] = [
  { id: "r_1", name: "Cleaning operative — Day shift", category: "Manpower", unit: "month", rate: 2400, last: "May 12", source: "Aqua Bright LLC", notes: "Includes uniforms & insurance" },
  { id: "r_2", name: "Deep cleaning per sqm", category: "Cleaning", unit: "sqm", rate: 6.5, last: "May 10", source: "Internal benchmark", notes: "Excl. consumables" },
  { id: "r_3", name: "HVAC filter — pleated MERV 8", category: "HVAC", unit: "pc", rate: 38, last: "May 9", source: "Camfil ME", notes: "20x20x2 std" },
  { id: "r_4", name: "AHU coil chemical clean", category: "HVAC", unit: "unit", rate: 480, last: "May 5", source: "Subcontractor — TKS", notes: "Per unit, <=15TR" },
  { id: "r_5", name: "Pest control — quarterly visit", category: "Pest Control", unit: "visit", rate: 350, last: "Apr 28", source: "Rentokil Boecker", notes: "1–3 BR residential" },
  { id: "r_6", name: "Generator inspection (<=500 kVA)", category: "Electrical", unit: "visit", rate: 650, last: "Apr 26", source: "PowerGen FZE", notes: "Monthly PPM" },
  { id: "r_7", name: "Plumbing repair allowance", category: "Plumbing", unit: "month", rate: 1200, last: "Apr 22", source: "Allowance", notes: "Materials excluded" },
  { id: "r_8", name: "Cleaning consumables kit", category: "Consumables", unit: "month", rate: 320, last: "Apr 18", source: "Sara Hygiene", notes: "Per 1000 sqm GFA" },
  { id: "r_9", name: "Safety officer — site visits", category: "Safety", unit: "day", rate: 720, last: "Apr 15", source: "Internal", notes: "Required for hot works" },
  { id: "r_10", name: "Civil patch repair (concrete)", category: "Civil", unit: "sqm", rate: 140, last: "Apr 11", source: "Al Naboodah", notes: "<=20mm depth" },
  { id: "r_11", name: "MV switchgear inspection", category: "Electrical", unit: "panel", rate: 1100, last: "Apr 8", source: "ABB AE", notes: "Annual PPM" },
  { id: "r_12", name: "Carpet shampooing", category: "Cleaning", unit: "sqm", rate: 4.2, last: "Apr 4", source: "Aqua Bright LLC", notes: "Min 200 sqm" },
];

export const seedNotes: Note[] = [
  { id: "n_1", title: "Client prefers monthly contract", body: "Marina Heights procurement said annual lump sum is hard to approve. Pitch monthly billing in cover letter.", tags: ["Marina Heights", "Pricing"], project: "p_1", pinned: true, when: "Today", createdAt: Date.now() - 1000 * 60 * 60 * 2 },
  { id: "n_2", title: "Confirm if consumables are included", body: "For DIFC scope, ask if chemicals + paper consumables fall under FM or tenant supply. Affects price by ~AED 4k.", tags: ["DIFC", "Scope"], project: "p_6", pinned: true, when: "Today", createdAt: Date.now() - 1000 * 60 * 60 * 3 },
  { id: "n_3", title: "Manager: re-check manpower calc", body: "Faisal flagged that I used 240 working hours; UAE standard is 208 for 5-day week. Re-run rates.", tags: ["Internal", "Action"], project: null, pinned: false, when: "Yesterday", createdAt: Date.now() - 1000 * 60 * 60 * 24 },
  { id: "n_4", title: "Need supplier rate for HVAC filters", body: "Camfil quoted 38 AED/pc but ask for bulk pricing >200 pcs. Also try AAF.", tags: ["HVAC", "Supplier"], project: "p_1", pinned: false, when: "Yesterday", createdAt: Date.now() - 1000 * 60 * 60 * 26 },
  { id: "n_5", title: "JLT — access only via service lift", body: "Building manager will issue gate passes 24h ahead. Tools >2m need approval.", tags: ["JLT", "Site"], project: "p_2", pinned: false, when: "2 days ago", createdAt: Date.now() - 1000 * 60 * 60 * 48 },
  { id: "n_6", title: "Boecker is incumbent at Yas Villas", body: "Renewal at AED 95k. We pitched 87k but lost on relationship. Lesson: lead with response time SLA.", tags: ["Lost", "Pest Control"], project: "p_7", pinned: false, when: "1 week ago", createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7 },
];

export const seedSiteVisits: SiteVisit[] = [
  {
    id: "sv_1",
    projectId: "p_3",
    title: "Al Quoz Warehouse",
    date: "14 May 2026",
    contact: "Mr. Khaled",
    phone: "+971 50 ... 2244",
    gfa: "34,000 sqm",
    hours: "06:00–18:00",
    notes:
      "Met building manager. Walked plantrooms and BoH. Filters replaced 4 months ago — 3 units on L12 need attention.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
];

export const seedChecklistItems: ChecklistItem[] = [
  { id: "ck_g1", siteVisitId: "sv_1", group: "General", text: "Take site photos (entrance, BoH, plantrooms)", done: true },
  { id: "ck_g2", siteVisitId: "sv_1", group: "General", text: "Confirm working hours & access windows", done: true },
  { id: "ck_g3", siteVisitId: "sv_1", group: "General", text: "Ask for floor plans / area takeoffs", done: false },
  { id: "ck_g4", siteVisitId: "sv_1", group: "General", text: "Check access restrictions (lifts, parking)", done: false },
  { id: "ck_g5", siteVisitId: "sv_1", group: "General", text: "Confirm contract duration & start date", done: true },
  { id: "ck_g6", siteVisitId: "sv_1", group: "General", text: "Note material responsibility (client vs FM)", done: false },
  { id: "ck_c1", siteVisitId: "sv_1", group: "Cleaning", text: "Count toilets / wash basins", done: true },
  { id: "ck_c2", siteVisitId: "sv_1", group: "Cleaning", text: "Measure carpet vs hard floor sqm", done: false },
  { id: "ck_c3", siteVisitId: "sv_1", group: "Cleaning", text: "Identify high-traffic vs low-traffic zones", done: false },
  { id: "ck_c4", siteVisitId: "sv_1", group: "Cleaning", text: "Confirm shift pattern (day / night / split)", done: true },
  { id: "ck_h1", siteVisitId: "sv_1", group: "HVAC", text: "Count AHU / FCU units & TR rating", done: true },
  { id: "ck_h2", siteVisitId: "sv_1", group: "HVAC", text: "Note filter sizes & accessibility", done: false },
  { id: "ck_h3", siteVisitId: "sv_1", group: "HVAC", text: "Check BMS availability & access", done: false },
  { id: "ck_e1", siteVisitId: "sv_1", group: "Electrical", text: "Identify panels & switchgear", done: false },
  { id: "ck_e2", siteVisitId: "sv_1", group: "Electrical", text: "Generator make, model, kVA rating", done: false },
  { id: "ck_e3", siteVisitId: "sv_1", group: "Electrical", text: "Standby UPS units & runtime", done: false },
  { id: "ck_p1", siteVisitId: "sv_1", group: "Plumbing", text: "Locate water tanks & pumps", done: true },
  { id: "ck_p2", siteVisitId: "sv_1", group: "Plumbing", text: "Booster pump make & maintenance log", done: false },
  { id: "ck_ci1", siteVisitId: "sv_1", group: "Civil", text: "Note facade type & accessibility", done: false },
  { id: "ck_ci2", siteVisitId: "sv_1", group: "Civil", text: "Identify any visible water damage / cracks", done: false },
  { id: "ck_s1", siteVisitId: "sv_1", group: "Safety", text: "Permit-to-work requirements", done: false },
  { id: "ck_s2", siteVisitId: "sv_1", group: "Safety", text: "PPE policy & induction needed?", done: true },
  { id: "ck_s3", siteVisitId: "sv_1", group: "Safety", text: "Fire / hot works restrictions", done: false },
];

export const seedRfqs: RFQ[] = [
  { id: "rfq_9", projectId: "p_9", name: "Dubai Hills Mall — Cleaning Top-Up", client: "Emaar Malls", status: "New", value: 0, priority: "Medium", dueDate: "May 24", next: "Receive scope by Thu" },
  { id: "rfq_10", projectId: "p_10", name: "Twofour54 HQ — HVAC Service", client: "Twofour54", status: "Site Visit", value: 0, priority: "High", dueDate: "May 18", next: "Site visit Sun 10am" },
  { id: "rfq_11", projectId: "p_11", name: "ADGM Tower Lobby Refresh", client: "ADGM", status: "Pricing", value: 0, priority: "Medium", dueDate: "May 21", next: "Confirm marble polish rate" },
  { id: "rfq_12", projectId: "p_12", name: "Sustainable City — Pest Control", client: "Diamond Developers", status: "Won", value: 124000, priority: "Low", dueDate: "—", next: "Mobilization week of 25 May" },
];

export const seedTemplates: Template[] = [
  { id: "t_1", name: "Cleaning estimate — Annual contract", icon: "spray", color: "green", rows: 14, used: 8, desc: "Manpower + consumables + deep clean cycles. Tuned for residential towers >= 10 floors.", kind: "estimate" },
  { id: "t_2", name: "HVAC PPM template", icon: "snow", color: "blue", rows: 9, used: 12, desc: "AHU / FCU filter, coil clean, BMS check, quarterly cycle. Includes filter takeoff sheet.", kind: "estimate" },
  { id: "t_3", name: "MEP reactive maintenance", icon: "bolt", color: "purple", rows: 11, used: 5, desc: "Call-out + materials allowance + on-call manpower. Good for small commercial.", kind: "estimate" },
  { id: "t_4", name: "Pest control quarterly", icon: "bug", color: "yellow", rows: 5, used: 9, desc: "BoH + common areas, 4 visits/year. Excl. bait stations & rodent traps.", kind: "estimate" },
  { id: "t_5", name: "Site visit report", icon: "clipboard", color: "gray", rows: 22, used: 18, desc: "Pre-filled checklist + observations + photo grid. Exports to PDF in 1 click.", kind: "checklist" },
  { id: "t_6", name: "Quotation assumptions", icon: "file", color: "orange", rows: 16, used: 14, desc: "Standard inclusions, exclusions, validity, payment terms. Edit per client.", kind: "report" },
];

export const seedActivity: ActivityItem[] = [
  { id: "a_1", who: "You", what: "saved estimate", on: "Marina Heights Tower — v3", when: "12 min ago", icon: "estimate", at: Date.now() - 1000 * 60 * 12 },
  { id: "a_2", who: "You", what: "added rate", on: "AHU coil chemical clean", when: "1h ago", icon: "rates", at: Date.now() - 1000 * 60 * 60 },
  { id: "a_3", who: "Faisal", what: "commented on", on: "JLT Cluster B — Reactive MEP", when: "2h ago", icon: "notes", at: Date.now() - 1000 * 60 * 60 * 2 },
  { id: "a_4", who: "You", what: "moved RFQ to Quotation Sent", on: "Marina Heights Tower", when: "3h ago", icon: "kanban", at: Date.now() - 1000 * 60 * 60 * 3 },
  { id: "a_5", who: "You", what: "completed site visit", on: "Al Quoz Warehouse", when: "Yesterday", icon: "site", at: Date.now() - 1000 * 60 * 60 * 24 },
  { id: "a_6", who: "You", what: "created project", on: "Mira Townhouses Landscaping", when: "Yesterday", icon: "projects", at: Date.now() - 1000 * 60 * 60 * 28 },
];

export const seedProjectTasks: ProjectTask[] = [
  { id: "pt_1", projectId: "p_1", text: "Get floor plans from client", done: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4 },
  { id: "pt_2", projectId: "p_1", text: "Confirm working hours & access", done: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3 },
  { id: "pt_3", projectId: "p_1", text: "Cost up manpower against UAE labour law", done: true, createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2 },
  { id: "pt_4", projectId: "p_1", text: "Send draft quotation for internal review", done: false, createdAt: Date.now() - 1000 * 60 * 60 * 24 },
  { id: "pt_5", projectId: "p_1", text: "Adjust markup after manager feedback", done: false, createdAt: Date.now() - 1000 * 60 * 60 * 12 },
  { id: "pt_6", projectId: "p_1", text: "Final quotation to client by Wed", done: false, createdAt: Date.now() - 1000 * 60 * 60 * 6 },
];

export const seedSettings: Settings = {
  personalName: "Ahmed H.",
  currency: "AED",
  defaultMarkup: 20,
  workingHours: "06:00 – 18:00",
  theme: "light",
  exportDefault: "PDF",
  notifications: true,
};
